// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRhD4ifw2KCmSy5FHM72CmSZNNZAKG7uk',
    appId: '1:810137797839:web:71401b96332f3c214223ba',
    messagingSenderId: '810137797839',
    projectId: 'prof-ci',
    authDomain: 'prof-ci.firebaseapp.com',
    storageBucket: 'prof-ci.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfe-NC1KEM2dKhBnOqmP973BftDhumq0Y',
    appId: '1:810137797839:android:9501b8a16cbe57b04223ba',
    messagingSenderId: '810137797839',
    projectId: 'prof-ci',
    storageBucket: 'prof-ci.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUS67eG0YCsRnVEePJfyTgOzt1BOnBoeM',
    appId: '1:810137797839:ios:5789517c29624a8a4223ba',
    messagingSenderId: '810137797839',
    projectId: 'prof-ci',
    storageBucket: 'prof-ci.firebasestorage.app',
    iosBundleId: 'com.example.profCi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUS67eG0YCsRnVEePJfyTgOzt1BOnBoeM',
    appId: '1:810137797839:ios:5789517c29624a8a4223ba',
    messagingSenderId: '810137797839',
    projectId: 'prof-ci',
    storageBucket: 'prof-ci.firebasestorage.app',
    iosBundleId: 'com.example.profCi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRhD4ifw2KCmSy5FHM72CmSZNNZAKG7uk',
    appId: '1:810137797839:web:8b08c6ba7806ab3c4223ba',
    messagingSenderId: '810137797839',
    projectId: 'prof-ci',
    authDomain: 'prof-ci.firebaseapp.com',
    storageBucket: 'prof-ci.firebasestorage.app',
  );
}
